config {
  type: "incremental",
  uniqueKey: ["firebase_id"],
  bigquery: {
    partitionBy: "registration_date",
    updatePartitionFilter:
        "registration_date >= date_sub(CURRENT_DATE('Asia/Manila'), interval 1 DAY)"
  }
}

SELECT * 
from ${ref("dim_xpost_accounts_view")}
-- ${when(incremental(), `where registration_date > (select max(registration_date) from ${self()})`)}
${when(incremental(), `WHERE registration_date >= DATE_SUB(CURRENT_DATE('Asia/Manila'), interval 1 DAY)`)}